import com.google.gson.annotations.SerializedName;

import java.util.Arrays;
import java.util.Objects;

public class Course {

    /**
     * {
     "CRN":41758,
     "Subject":"AAS",
     "Number":100,
     "Title":"Intro Asian American Studies",
     "Section":"AD1",
     "Type":"DIS",
     "Term":120138,
     "Instructor":"Arai, Sayuri",
     "Grades":[
     6,
     16,
     5,
     3,
     2,
     3,
     0,
     0,
     0,
     0,
     0,
     0,
     0,
     0
     ],
     "Average":3.72
     }
     */

    private String exampleCourse = "";

    /**
     * Autogenerated equals function.
     * @param o
     * @return
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Course course = (Course) o;
        return crn == course.crn && number == course.number && term == course.term && Double.compare(course.average, average) == 0 && Objects.equals(subject, course.subject) && Objects.equals(title, course.title) && Objects.equals(section, course.section) && Objects.equals(type, course.type) && Objects.equals(instructor, course.instructor) && Arrays.equals(grades, course.grades);
    }

    @Override
    public int hashCode() {
        return 0;
    }

    @SerializedName("CRN")
    private int crn;

    @SerializedName("Subject")
    private String subject;

    @SerializedName("Number")
    private int number;

    @SerializedName("Title")
    private String title;

    @SerializedName("Section")
    private String section;

    @SerializedName("Type")
    private String type;

    @SerializedName("Term")
    private int term;

    @SerializedName("Instructor")
    private String instructor;

    @SerializedName("Grades")
    private int[] grades;

    @SerializedName("Average")
    private double average;

    public int getCrn() {
        return crn;
    }

    public String getSubject() {
        return subject;
    }

    public int getNumber() {
        return number;
    }

    public String getTitle() {
        return title;
    }

    public String getSection() {
        return section;
    }

    public String getType() {
        return type;
    }

    public int getTerm() {
        return term;
    }

    public String getInstructor() {
        return instructor;
    }

    public int[] getGrades() {
        return grades;
    }

    public double getAverage() {
        return average;
    }

    public Course(int crn) {
    }

    /**public static String listCoursesToString(ArrayList<Course>[] courseArrayList ) {

        StringBuilder coursesStringBuilder = new StringBuilder();
        return coursesStringBuilder.toString();
    }  */

}
